var hours = [
  { value: "01", label: "01" },
  { value: "02", label: "02" },
  { value: "03", label: "03" },
  { value: "04", label: "04" },
  { value: "05", label: "05" },
  { value: "06", label: "06" },
  { value: "07", label: "07" },
  { value: "08", label: "08" },
  { value: "09", label: "09" },
  { value: "10", label: "10" },
  { value: "11", label: "11" },
  { value: "12", label: "12" },
];

var minutes = [
  { value: "00", label: "00" },
  { value: "01", label: "01" },
  { value: "02", label: "02" },
  { value: "03", label: "03" },
  { value: "04", label: "04" },
  { value: "05", label: "05" },
  { value: "06", label: "06" },
  { value: "07", label: "07" },
  { value: "08", label: "08" },
  { value: "09", label: "09" },
  { value: "10", label: "10" },
  { value: "11", label: "11" },
  { value: "12", label: "12" },
  { value: "13", label: "13" },
  { value: "14", label: "14" },
  { value: "15", label: "15" },
  { value: "16", label: "16" },
  { value: "17", label: "17" },
  { value: "18", label: "18" },
  { value: "19", label: "19" },
  { value: "20", label: "20" },
  { value: "21", label: "21" },
  { value: "22", label: "22" },
  { value: "23", label: "23" },
  { value: "24", label: "24" },
  { value: "25", label: "25" },
  { value: "26", label: "26" },
  { value: "27", label: "27" },
  { value: "28", label: "28" },
  { value: "29", label: "29" },
  { value: "30", label: "30" },
  { value: "31", label: "31" },
  { value: "32", label: "32" },
  { value: "33", label: "33" },
  { value: "34", label: "34" },
  { value: "35", label: "35" },
  { value: "36", label: "36" },
  { value: "37", label: "37" },
  { value: "38", label: "38" },
  { value: "39", label: "39" },
  { value: "40", label: "40" },
  { value: "41", label: "41" },
  { value: "42", label: "42" },
  { value: "43", label: "43" },
  { value: "44", label: "44" },
  { value: "45", label: "45" },
  { value: "46", label: "46" },
  { value: "47", label: "47" },
  { value: "48", label: "48" },
  { value: "49", label: "49" },
  { value: "50", label: "50" },
  { value: "51", label: "51" },
  { value: "52", label: "52" },
  { value: "53", label: "53" },
  { value: "54", label: "54" },
  { value: "55", label: "55" },
  { value: "56", label: "56" },
  { value: "57", label: "57" },
  { value: "58", label: "58" },
  { value: "59", label: "59" },
];

var ampm = [
  { value: "am", label: "am" },
  { value: "pm", label: "pm" },
];

var postStatus = [
  { value: "draft", label: "Draft" },
  { value: "published", label: "Published" },
];

var postTypes = [
  { value: "post", label: "Post" },
  { value: "rockstar", label: "Rockstar" },
];

var requestType = [
  { value: "raw", label: "Raw Data" },
  { value: "report", label: "New Report" },
  { value: "enhacement", label: "Report Enhancement" },
  { value: "error", label: "Error Detected" },
];

var requestFrequency = [
  { value: "ad_hoc", label: "Ad-Hoc" },
  { value: "daily", label: "Daily" },
  { value: "weekly", label: "Weekly" },
  { value: "monthly", label: "Monthly" },
  { value: "bi_monthly", label: "Bi-Monthly" },
  { value: "other", label: "Other" },
];

var requestPriority = [
  { value: 1, label: "Urgent" },
  { value: 2, label: "Very Important" },
  { value: 3, label: "Important" },
  { value: 4, label: "Nice to have" },
];

var requestStatus = [
  { value: "open", label: "Open" },
  { value: "in_progress", label: "In Progress" },
  { value: "closed", label: "Closed" },
  { value: "on_hold", label: "On Hold" },
];

var userRole = [
  { value: "client", label: "Client" },
  { value: "assignee", label: "Assignee" },
  { value: "top", label: "Top" },
  { value: "rockstar", label: "Rockstar" },
];
var countryList = [
  { value: "Albania", label: "Albania" },
  { value: "Algeria", label: "Algeria" },
  { value: "American Samoa", label: "American Samoa" },
  { value: "Andorra", label: "Andorra" },
  { value: "Angola", label: "Angola" },
  { value: "Anguilla", label: "Anguilla" },
  { value: "Antartica", label: "Antartica" },
  { value: "Antigua &amp; Barbuda", label: "Antigua &amp; Barbuda" },
  { value: "Argentina", label: "Argentina" },
  { value: "Aruba", label: "Aruba" },
  { value: "Australia", label: "Australia" },
  { value: "Austria", label: "Austria" },
  { value: "Azerbaijan", label: "Azerbaijan" },
  { value: "Bahamas", label: "Bahamas" },
  { value: "Bahrain", label: "Bahrain" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Barbados", label: "Barbados" },
  { value: "Belarus", label: "Belarus" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Bangladesh", label: "Bangladesh" },
  { value: "Belgium", label: "Belgium" },
  { value: "Belize", label: "Belize" },
  { value: "Belize", label: "Bangladesh" },
  { value: "Benin", label: "Benin" },
  { value: "Bermuda", label: "Bermuda" },
  { value: "Bhutan", label: "Bhutan" },
  { value: "Bolivia", label: "Bolivia" },
  { value: "Bosnia &amp; Herzegowina", label: "Bosnia &amp; Herzegowina" },
  { value: "Botswana", label: "Botswana" },
  { value: "Bouvet Island", label: "Bouvet Island" },
  { value: "Brasil", label: "Brasil" },
  {
    value: "British IndeanOcean Territory",
    label: "British IndeanOcean Territory",
  },
  { value: "Brunei Darussalam", label: "Brunei Darussalam" },
  { value: "Bulgaria", label: "Bulgaria" },
  { value: "Burkina Faso", label: "Burkina Faso" },
  { value: "Burundi", label: "Burundi" },
  { value: "Cambodia", label: "Cambodia" },
  { value: "Cameroon", label: "Cameroon" },
  { value: "Canadá", label: "Canadá" },
  { value: "Cape Verde", label: "Cape Verde" },
  { value: "Cayman Islands", label: "Cayman Islands" },
  { value: "Central African Republic", label: "Central African Republic" },
  { value: "Chad", label: "Chad" },
  { value: "China", label: "China" },
  { value: "Christmas Island", label: "Christmas Island" },
  { value: "Cocos Islands", label: "Cocos Islands" },
  { value: "Colombia", label: "Colombia" },
  { value: "Comoros", label: "Comoros" },
  { value: "Congo, Democratic Republic", label: "Congo, Democratic Republic" },
  { value: "Congo, People's Republic", label: "Congo, People's Republic" },
  { value: "Cook Islands", label: "Cook Islands" },
  { value: "Costa Rica", label: "Costa Rica" },
  { value: "Cote D'lvoire", label: "Cote D'lvoire" },
  { value: "Croatia", label: "Croatia" },
  { value: "Cuba", label: "Cuba" },
  { value: "Cyprus", label: "Cyprus" },
  { value: "Czech Republic", label: "Czech Republic" },
  { value: "Denmark", label: "Denmark" },
  { value: "Djibouti", label: "Djibouti" },
  { value: "Dominicana", label: "Dominicana" },
  { value: "Dominican Republic", label: "Dominican Republic" },
  { value: "East Timor", label: "East Timor" },
  { value: "Ecuador", label: "Ecuador" },
  { value: "Egypt", label: "Egypt" },
  { value: "El Salvador", label: "El Salvador" },
  { value: "Equatorial Guinea", label: "Equatorial Guinea" },
  { value: "Eritrea", label: "Eritrea" },
  { value: "Estados Unidos", label: "Estados Unidos" },
  { value: "Falkland Islands", label: "Falkland Islands" },
  { value: "Ethiopia", label: "Ethiopia" },
  { value: "Faroe Islands", label: "Faroe Islands" },
  { value: "Fiji", label: "Fiji" },
  { value: "France", label: "France" },
  { value: "French Guiana", label: "French Guiana" },
  { value: "French Polynesia", label: "French Polynesia" },
  {
    value: "French Southern Territories",
    label: "French Southern Territories",
  },
  { value: "Gabon", label: "Gabon" },
  { value: "Gambia", label: "Gambia" },
  { value: "Georgia", label: "Georgia" },
  { value: "Germany", label: "Germany" },
  { value: "Ghana", label: "Ghana" },
  { value: "Gibraltar", label: "Gibraltar" },
  { value: "Greece", label: "Greece" },
  { value: "Greenland", label: "Greenland" },
  { value: "Grenada", label: "Grenada" },
  { value: "Guadeloupe", label: "Guadeloupe" },
  { value: "Guam", label: "Guam" },
  { value: "Guatemala", label: "Guatemala" },
  { value: "Guinea", label: "Guinea" },
  { value: "Guinea-Bissau", label: "Guinea-Bissau" },
  { value: "Guyana", label: "Guyana" },
  { value: "Haiti", label: "Haiti" },
  { value: "Heard McDonaldIslands", label: "Heard McDonaldIslands" },
  { value: "Honduras", label: "Honduras" },
  { value: "Hong Kong", label: "Hong Kong" },
  { value: "Hungary", label: "Hungary" },
  { value: "Iceland", label: "Iceland" },
  { value: "India", label: "India" },
  { value: "Indonesia", label: "Indonesia" },
  { value: "Irán", label: "Irán" },
  { value: "Iraq", label: "Iraq" },
  { value: "Ireland", label: "Ireland" },
  { value: "Israel", label: "Israel" },
  { value: "Italy", label: "Italy" },
  { value: "Jamaica", label: "Jamaica" },
  { value: "Japan", label: "Japan" },
  { value: "Jordan", label: "Jordan" },
  { value: "Kazakhstan", label: "Kazakhstan" },
  { value: "Kenya", label: "Kenya" },
  { value: "Kiribati", label: "Kiribati" },
  { value: "Korea, North", label: "Korea, North" },
  { value: "Korea, South", label: "Korea, South" },
  { value: "Kuwait", label: "Kuwait" },
  { value: "Kyrgyzstan", label: "Kyrgyzstan" },
  { value: "Lao", label: "Lao" },
  { value: "Latvia", label: "Latvia" },
  { value: "Lebanon", label: "Lebanon" },
  { value: "Lesotho", label: "Lesotho" },
  { value: "Liberia", label: "Liberia" },
  { value: "Libya", label: "Libya" },
  { value: "Liechtenstein", label: "KiLiechtensteinribati" },
  { value: "Lithuania", label: "Lithuania" },
  { value: "Luxembourg", label: "Luxembourg" },
  { value: "Macau", label: "Macau" },
  { value: "Macedonia", label: "Macedonia" },
  { value: "Madagascar", label: "Madagascar" },
  { value: "Malawi", label: "Malawi" },
  { value: "Malaysia", label: "Malaysia" },
  { value: "Maldives", label: "Maldives" },
  { value: "Marshall Islands", label: "Marshall Islands" },
  { value: "Martinique", label: "Martinique" },
  { value: "Mauritania", label: "Mauritania" },
  { value: "Mauritius", label: "Mauritius" },
  { value: "Mayotte", label: "Mayotte" },
  { value: "México", label: "México" },
  { value: "Micronesia", label: "Micronesia" },
  { value: "Moldova", label: "Moldova" },
  { value: "Monaco", label: "Monaco" },
  { value: "Mongolia", label: "Mongolia" },
  { value: "Montenegro", label: "Montenegro" },
  { value: "Montserrat", label: "Montserrat" },
  { value: "Morocco", label: "Morocco" },
  { value: "Mozambique", label: "Mozambique" },
  { value: "Myanmar", label: "Myanmar" },
  { value: "Namibia", label: "Namibia" },
  { value: "Nauru", label: "Nauru" },
  { value: "Nepal", label: "Nepal" },
  { value: "Netherlands", label: "Netherlands" },
  { value: "Netherlands Antilles", label: "Netherlands Antilles" },
  { value: "New Caledonia", label: "New Caledonia" },
  { value: "New Zealand", label: "New Zealand" },
  { value: "Nicaragua", label: "Nicaragua" },
  { value: "Níger", label: "Níger" },
  { value: "Nigeria", label: "Nigeria" },
  { value: "Norfolk Island", label: "Norfolk Island" },
  { value: "Northern MarianaIslands", label: "Northern MarianaIslands" },
  { value: "Norway", label: "Norway" },
  { value: "Otros Países", label: "Otros Países" },
  { value: "Pakistan", label: "Pakistan" },
  { value: "Palestinian Territory", label: "Palestinian Territory" },
  { value: "Panamá", label: "Panamá" },
  { value: "Papua New Guinea", label: "Papua New Guinea" },
  { value: "Paraguay", label: "Paraguay" },
  { value: "Perú", label: "Perú" },
  { value: "Philippines", label: "Philippines" },
  { value: "Pitcairn", label: "Pitcairn" },
  { value: "Poland", label: "Poland" },
  { value: "Portugal", label: "Portugal" },
  { value: "Puerto Rico", label: "Puerto Rico" },
  { value: "Qatar", label: "Qatar" },
  { value: "Reunion", label: "Reunion" },
  { value: "Romania", label: "Romania" },
  { value: "Russian Federation", label: "Russian Federation" },
  { value: "Rwanda", label: "Rwanda" },
  { value: "Samoa", label: "Samoa" },
  { value: "San Marino", label: "San Marino" },
  { value: "Sao Tome &amp; Principe", label: "Sao Tome &amp; Principe" },
  { value: "Saudi Arabia", label: "Saudi Arabia" },
  { value: "Senegal", label: "Senegal" },
  { value: "Seychelles", label: "Seychelles" },
  { value: "Sierra Leone", label: "Sierra Leone" },
  { value: "Singapore", label: "Singapore" },
  { value: "Slovakia", label: "Slovakia" },
  { value: "Slovenia", label: "Slovenia" },
  { value: "Solomon Islands", label: "Solomon Islands" },
  { value: "Somalia", label: "Somalia" },
  { value: "South Africa", label: "South Africa" },
  { value: "Spain", label: "Spain" },
  { value: "St. Helena", label: "St. Helena" },
  { value: "St. Lucia", label: "St. Lucia" },
  { value: "St. Pierre And Miquelon", label: "St. Pierre And Miquelon" },
  {
    value: "St. Vincent &amp; Grenadines",
    label: "St. Vincent &amp; Grenadines",
  },
  { value: "Sudan", label: "Sudan" },
  {
    value: "Svalbard &amp; Jan Mayen Islands",
    label: "Svalbard &amp; Jan Mayen Islands",
  },
  { value: "Tunisia", label: "Tunisia" },
  { value: "Turkmenistan", label: "Turkmenistan" },
  { value: "Turks &amp; Caicos Islands", label: "Turks &amp; Caicos Islands" },
  { value: "Tuvalu", label: "Tuvalu" },
  {
    value: "U. S. MinorOutlying Islands",
    label: "U. S. MinorOutlying Islands",
  },
  { value: "Uganda", label: "Uganda" },
  { value: "United Arab Emirates", label: "United Arab Emirates" },
  { value: "United Kingdom", label: "United Kingdom" },
  { value: "Uruguay", label: "Uruguay" },
];
var ticketCategory = [
  { value: "APIS (ERROR HUMANO)", label: "APIS (ERROR HUMANO)" },
  { value: "APIS (ERROR SISTEMA)", label: "APIS (ERROR SISTEMA)" },
  {
    value: "CERTIFICADO DE VACUNA CONTRA LA FIEBRE AMARILLA",
    label: "CERTIFICADO DE VACUNA CONTRA LA FIEBRE AMARILLA",
  },
  { value: "COVID19 (PRUEBA FALSA)", label: "COVID19 (PRUEBA FALSA)" },
  { value: "COVID19 (SIN PRUEBA)", label: "COVID19 (SIN PRUEBA)" },
  {
    value: "DOCUMENTOS SECUNDARIOS FALSOS",
    label: "DOCUMENTOS SECUNDARIOS FALSOS",
  },
  {
    value: "ERROR DE VALIDACIÓN (TIMATIC UPDATE)",
    label: "ERROR DE VALIDACIÓN (TIMATIC UPDATE)",
  },
  { value: "FORMULARIO DE SALUD", label: "FORMULARIO DE SALUD" },
  {
    value: "FORMULARIO MIGRATORIO DIGITAL",
    label: "FORMULARIO MIGRATORIO DIGITAL",
  },
  { value: "INTERCEPCION CM EN ORIGEN", label: "INTERCEPCION CM EN ORIGEN" },
  {
    value: "INTERCEPCION CM EN ORIGEN (REQUISITOS DE AUTORIDADES MEXICANAS)",
    label: "INTERCEPCION CM EN ORIGEN (REQUISITOS DE AUTORIDADES MEXICANAS)",
  },
  {
    value: "NOMBRE DIFERENTE A LOS BOLETOS",
    label: "NOMBRE DIFERENTE A LOS BOLETOS",
  },
  { value: "PASAPORTE DETERIORADO", label: "PASAPORTE DETERIORADO" },
  { value: "PASAPORTE SIN VIGENCIA", label: "PASAPORTE SIN VIGENCIA" },
  { value: "PAX ABORDO NO MANIFESTADO", label: "PAX ABORDO NO MANIFESTADO" },
  {
    value: "PAX CON CUSTODIO INTERNACIONAL",
    label: "PAX CON CUSTODIO INTERNACIONAL",
  },
  {
    value: "PAX CONECTANDO DE OTRAS AEROLÍNEAS",
    label: "PAX CONECTANDO DE OTRAS AEROLÍNEAS",
  },
  {
    value: "PAX INADMITIDO NO REPORTADO EN ESTACIÓN",
    label: "PAX INADMITIDO NO REPORTADO EN ESTACIÓN",
  },
  {
    value: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (BOLETO DE RETORNO)",
    label: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (BOLETO DE RETORNO)",
  },
  {
    value: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (ECONÓMICO)",
    label: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (ECONÓMICO)",
  },
  {
    value: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (HOSPEDAJE)",
    label: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (HOSPEDAJE)",
  },
  {
    value: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (NORMAS BIO)",
    label: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (NORMAS BIO)",
  },
  {
    value: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (PERFIL)",
    label: "PAX RECHAZADO/INADMITIDO POR MIGRACIÓN (PERFIL)",
  },
  { value: "PAX REFUGIADO", label: "PAX REFUGIADO" },
  {
    value: "SIN BOLETO DE REGRESO Y/O SALIDA",
    label: "SIN BOLETO DE REGRESO Y/O SALIDA",
  },
  { value: "SIN PASADO JUDICIAL", label: "SIN PASADO JUDICIAL" },
  { value: "SIN PASAPORTE", label: "SIN PASAPORTE" },
  { value: "SIN PERMISO DE ENTRADA", label: "SIN PERMISO DE ENTRADA" },
  {
    value: "SIN PERMISO DE ENTRADA (CUSTODIO POR EMERGENCIA MEDICA)",
    label: "SIN PERMISO DE ENTRADA (CUSTODIO POR EMERGENCIA MEDICA)",
  },
  {
    value: "SIN PERMISO DE ENTRADA (CUSTODIO POR OI)",
    label: "SIN PERMISO DE ENTRADA (CUSTODIO POR OI)",
  },
  {
    value: "SIN PERMISO DE ENTRADA (CUSTODIO POR OVS)",
    label: "SIN PERMISO DE ENTRADA (CUSTODIO POR OVS)",
  },
  { value: "SIN RESIDENCIA", label: "SIN RESIDENCIA" },
  { value: "SIN TARJETA DE TURISMO", label: "SIN TARJETA DE TURISMO" },
  { value: "SIN VISA", label: "SIN VISA" },
  {
    value: "TÁNSITO PTY MAYOR A 12 HORAS",
    label: "TÁNSITO PTY MAYOR A 12 HORAS",
  },
  { value: "VISA FALSA", label: "VISA FALSA" },
  { value: "VISA VENCIDA", label: "VISA VENCIDA" },
];
var stationList = [
  { value: "ADZ", label: "ADZ" },
  { value: "ASU", label: "ASU" },
  { value: "ATL", label: "ATL" },
  { value: "AUA", label: "AUA" },
  { value: "AXM", label: "AXM" },
  { value: "BAQ", label: "BAQ" },
  { value: "BGA", label: "BGA" },
  { value: "BGI", label: "BGI" },
  { value: "BOG", label: "BOG" },
  { value: "BOS", label: "BOS" },
  { value: "BSB", label: "BSB" },
  { value: "BZE", label: "BZE" },
  { value: "CCS", label: "CCS" },
  { value: "CIX", label: "CIX" },
  { value: "CLO", label: "CLO" },
  { value: "CNF", label: "CNF" },
  { value: "COR", label: "COR" },
  { value: "CTG", label: "CTG" },
  { value: "CUC", label: "CUC" },
  { value: "CUN", label: "CUN" },
  { value: "CUC", label: "CUC" },
  { value: "CUR", label: "CUR" },
  { value: "DAV", label: "DAV" },
  { value: "DEN", label: "DEN" },
  { value: "EZE", label: "EZE" },
  { value: "FLL", label: "FLL" },
  { value: "FOR", label: "FOR" },
  { value: "GDL", label: "GDL" },
  { value: "GEO", label: "GEO" },
  { value: "GIG", label: "GIG" },
  { value: "GRU", label: "GRU" },
  { value: "GUA", label: "GUA" },
  { value: "GYE", label: "GYE" },
  { value: "HAV", label: "HAV" },
  { value: "HOG", label: "HOG" },
  { value: "IAD", label: "IAD" },
  { value: "JFK", label: "JFK" },
  { value: "KIN", label: "KIN" },
  { value: "LAS", label: "LAS" },
  { value: "LAX", label: "LAX" },
  { value: "LIM", label: "LIM" },
  { value: "LIR", label: "LIR" },
  { value: "MAO", label: "MAO" },
  { value: "MAR", label: "MAR" },
  { value: "MBJ", label: "MBJ" },
  { value: "MCO", label: "MCO" },
  { value: "MDE", label: "MDE" },
  { value: "MDZ", label: "MDZ" },
  { value: "MEX", label: "MEX" },
  { value: "MGA", label: "MGA" },
  { value: "MIA", label: "MIA" },
  { value: "MSY", label: "MSY" },
  { value: "MTY", label: "MTY" },
  { value: "MVD", label: "MVD" },
  { value: "NAS", label: "NAS" },
  { value: "ORD", label: "ORD" },
  { value: "PAP", label: "PAP" },
  { value: "PBM", label: "PBM" },
  { value: "PEI", label: "PEI" },
  { value: "POA", label: "POA" },
  { value: "POS", label: "POS" },
  { value: "PTY", label: "PTY" },
  { value: "PUJ", label: "PUJ" },
  { value: "PVR", label: "PVR" },
  { value: "REC", label: "REC" },
  { value: "ROS", label: "ROS" },
  { value: "SAL", label: "SAL" },
  { value: "SAP", label: "SAP" },
  { value: "SCL", label: "SCL" },
  { value: "SDQ", label: "SDQ" },
  { value: "SFO", label: "SFO" },
  { value: "SDQ", label: "SDQ" },
  { value: "SJO", label: "SJO" },
  { value: "SJU", label: "SJU" },
  { value: "SLA", label: "SLA" },
  { value: "SNU", label: "SNU" },
  { value: "SSA", label: "SSA" },
  { value: "STI", label: "STI" },
  { value: "SXM", label: "SXM" },
  { value: "TGU", label: "TGU" },
  { value: "TPA", label: "TPA" },
  { value: "UIO", label: "UIO" },
  { value: "VLN", label: "VLN" },
  { value: "VVI", label: "VVI" },
  { value: "XPL", label: "XPL" },
  { value: "YUL", label: "YUL" },
  { value: "YYZ", label: "YYZ" },
];

var reportStation = [
  { value: "ADZ", label: "ADZ" },
  { value: "ASU", label: "ASU" },
  { value: "ATL", label: "ATL" },
  { value: "AUA", label: "AUA" },
  { value: "AXM", label: "AXM" },
  { value: "BAQ", label: "BAQ" },
  { value: "BGA", label: "BGA" },
  { value: "BGI", label: "BGI" },
  { value: "BOG", label: "BOG" },
  { value: "BOS", label: "BOS" },
  { value: "BSB", label: "BSB" },
  { value: "BZE", label: "BZE" },
  { value: "CCS", label: "CCS" },
  { value: "CIX", label: "CIX" },
  { value: "CLO", label: "CLO" },
  { value: "CNF", label: "CNF" },
  { value: "COR", label: "COR" },
  { value: "CTG", label: "CTG" },
  { value: "CUC", label: "CUC" },
  { value: "CUN", label: "CUN" },
  { value: "CUC", label: "CUC" },
  { value: "CUR", label: "CUR" },
  { value: "DAV", label: "DAV" },
  { value: "DEN", label: "DEN" },
  { value: "EZE", label: "EZE" },
  { value: "FLL", label: "FLL" },
  { value: "FOR", label: "FOR" },
  { value: "GDL", label: "GDL" },
  { value: "GEO", label: "GEO" },
  { value: "GIG", label: "GIG" },
  { value: "GRU", label: "GRU" },
  { value: "GUA", label: "GUA" },
  { value: "GYE", label: "GYE" },
  { value: "HAV", label: "HAV" },
  { value: "HOG", label: "HOG" },
  { value: "IAD", label: "IAD" },
  { value: "JFK", label: "JFK" },
  { value: "KIN", label: "KIN" },
  { value: "LAS", label: "LAS" },
  { value: "LAX", label: "LAX" },
  { value: "LIM", label: "LIM" },
  { value: "LIR", label: "LIR" },
  { value: "MAO", label: "MAO" },
  { value: "MAR", label: "MAR" },
  { value: "MBJ", label: "MBJ" },
  { value: "MCO", label: "MCO" },
  { value: "MDE", label: "MDE" },
  { value: "MDZ", label: "MDZ" },
  { value: "MEX", label: "MEX" },
  { value: "MGA", label: "MGA" },
  { value: "MIA", label: "MIA" },
  { value: "MSY", label: "MSY" },
  { value: "MTY", label: "MTY" },
  { value: "MVD", label: "MVD" },
  { value: "NAS", label: "NAS" },
  { value: "ORD", label: "ORD" },
  { value: "PAP", label: "PAP" },
  { value: "PBM", label: "PBM" },
  { value: "PEI", label: "PEI" },
  { value: "POA", label: "POA" },
  { value: "POS", label: "POS" },
  { value: "PTY", label: "PTY" },
  { value: "PUJ", label: "PUJ" },
  { value: "PVR", label: "PVR" },
  { value: "REC", label: "REC" },
  { value: "ROS", label: "ROS" },
  { value: "SAL", label: "SAL" },
  { value: "SAP", label: "SAP" },
  { value: "SCL", label: "SCL" },
  { value: "SDQ", label: "SDQ" },
  { value: "SFO", label: "SFO" },
  { value: "SDQ", label: "SDQ" },
  { value: "SJO", label: "SJO" },
  { value: "SJU", label: "SJU" },
  { value: "SLA", label: "SLA" },
  { value: "SNU", label: "SNU" },
  { value: "SSA", label: "SSA" },
  { value: "STI", label: "STI" },
  { value: "SXM", label: "SXM" },
  { value: "TGU", label: "TGU" },
  { value: "TPA", label: "TPA" },
  { value: "UIO", label: "UIO" },
  { value: "VLN", label: "VLN" },
  { value: "VVI", label: "VVI" },
  { value: "XPL", label: "XPL" },
  { value: "YUL", label: "YUL" },
  { value: "YYZ", label: "YYZ" },
];
var listInbound = [
  { value: "100", label: "100" },
  { value: "101", label: "101" },
];

var wclOptions = [
  { value: "SI", label: "SI" },
  { value: "NO", label: "NO" },
];
var interceptorOptions = [
  { value: "Migracion", label: "Migración" },
  { value: "AgentCM", label: "Agente de CM" },
];
var resMigrOptions = [
  { value: "Rechazado", label: "Rechazado" },
  { value: "ApSpecialMang", label: "Admitido/Manejo Especial", }
];

var authSanctionOptions = [
  { value: "SI", label: "SI" },
  { value: "NO", label: "NO", }
];
var authCostOptions = [
  { value: "SI", label: "SI" },
  { value: "NO", label: "NO", }
];
var feeAppealOptions = [
  { value: "SI", label: "SI" },
  { value: "NO", label: "NO" }
];

var feeProviderNotiOptions = [
  { value: "SI", label: "SI" },
  { value: "NO", label: "NO" }
];
var supplierCostOptions = [
  { value: "SI", label: "SI" },
  { value: "NO", label: "NO" }
];
var supplierStatusOptions = [
  { value: "En espera de pago", label: "En espera de pago" },
  { value: "Pendiente facturar", label: "Pendiente facturar" },
  { value: "Multa recuperada", label: "Multa recuperada" },
  { value: "Apelada", label: "Apelada" },
  { value: "Multa No recuperable", label: "Multa No recuperable" },
];
var feedNotRecoveredReasonsOptions = [
  { value: "En espera de pago", label: "En espera de pago" },
  { value: "Pendiente facturar", label: "Pendiente facturar" },
  { value: "Multa recuperada", label: "Multa recuperada" },
  { value: "Apelada", label: "Apelada" },
  { value: "Multa No recuperable", label: "Multa No recuperable" },
];
var societyContableStatusOptions = [
  { value: "Pendiente por pagar", label: "Pendiente por pagar" },
  { value: "Generar factura cobro proveedor", label: "Generar factura cobro proveedor" },
  { value: "Multa pagada", label: "Multa pagada" }
];
var statusCustodyOptions = [
  { value: "Pendiente pagar custodio", label: "Pendiente pagar custodio" },
  { value: "Custodio pagado", label: "Custodio pagado" }
];
module.exports = {
  statusCustodyOptions,
  societyContableStatusOptions,
  feedNotRecoveredReasonsOptions,
  supplierStatusOptions,
  supplierCostOptions,
  feeProviderNotiOptions,
  feeAppealOptions,
  authCostOptions,
  resMigrOptions,
  authSanctionOptions,
  interceptorOptions,
  listInbound,
  wclOptions,
  hours,
  minutes,
  ampm,
  postStatus,
  postTypes,
  requestType,
  requestFrequency,
  requestPriority,
  requestStatus,
  userRole,
  ticketCategory,
  reportStation,
  stationList,
};
